### ISSUE TITLE
Check skipped sequence?

### ISSUE THREAD

**Issue by mschubert** [fulcrumgenomics/fqtk#21]
I started using `fqtk` yesterday, and it's really easy to install, plus nice and quick to use with a clear help page :+1: 

Right now, we can specify the [read structure](https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures) using barcode `B`, skipped `S`, molecular `M` and template `T`. A `S`kipped part may occur:

> for example if they are monotemplate sequence generated by the library preparation

I was wondering: would it make sense to provide an option to check if the skipped sequence matches the monotemplate (and allow a certain amount of mismatches there as well)?

**Comment by nh13** [comment]
@tfenne may disagree, but similar to how [correcting](http://fulcrumgenomics.github.io/fgbio/tools/latest/CorrectUmis.html) or [grouping](http://fulcrumgenomics.github.io/fgbio/tools/latest/GroupReadsByUmi.html) molecular barcodes are separate tools, I would argue that checking the monotemplate is not related to sample demultiplexing, so could be handled downstream.  For example, changing S to T for those bases during sample demultiplexing to retain those reads, then having a second tool to filter reads with noisy monotemplates and remove the monotemplate in those that are kept.  This follows the model of small, purpose-built tools, which are easier to implement, often more efficient, and more maintainable.

As for a tool for monotemplate checking, I'd be curious what you're seeing in your data that leads you to want one?

**Comment by mschubert** [comment]
Thanks for your answer!

My FASTQs do not really have a monotemplate, but two different primer sequences for two locations in the genome (TCRa + TCRb sequencing). So the read structure I have is like this:

* `7B15S+T`
* `7B20S+T`

I would like to split this file into different FASTQ files depending on the `7B`, but only retain either of the two `S` sequences.

As you suggest, I can of course change the `S` into a `T`, and run `fqtk` twice, with one each of:

* `7T15S+T`
* `7T20S+T`

This will give me, per run, two output files: `runN.R1.fq.gz` which has the sample barcode, and `runN.R2.fq.gz` which contains the genomic sequence.

However, then I'd want to split `runN.R2.fq.gz` by the barcodes in `runN.R1.fq.gz`, which (as far as I understand) does not work.

**Comment by mschubert** [comment]
Yes, that's (more or less) what I realized I could do after writing the last post:

* Split `7B+T`
* For each, split `15B+T` on run one, `20B+T` on run two (leaving the respective other to be unassigned)

So definitely possible using `fqtk` with its current capabilities, albeit a bit cumbersome. If you want to keep `fqtk demux` as simple as possible I can of course understand that.

**Comment by nh13** [comment]
I think if other folks have the same need, it's something we could add.  I'm glad it's working for you!
