### ISSUE TITLE
Fails if sample barcodes in the meta.csv are longer than implied by the read structure

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fqtk#28]
This panics in `count_mismatches` but should be caught early in the tool.

**Comment by TimD1** [comment]
This panic was fixed in commit ae91e90e; the current behavior is to not demultiplex the read if the barcode is longer:
https://github.com/fulcrumgenomics/fqtk/blob/6ed98a3334eb13f22dd8054d39d9b8f77e76b337/src/lib/barcode_matching.rs#L130-L133
