### ISSUE TITLE
Barcodes only in Read 1

### ISSUE THREAD

**Issue by ahish-sujay** [fulcrumgenomics/fqtk#40]
Hi! I was curious to know if the tool would be able to split paired-end FASTQ files that have a barcode close to the end of the read in only Read 1? I wasn't 100% sure and could not really figure it out from the documentation. Thanks!

**Comment by nh13** [comment]
Is the barcode in a fixed location, or is it at a variable location?

**Comment by ahish-sujay** [comment]
Oops, I completely missed, sorry! Thank you so much, will take a look at this as to how to specify the read structure.

**Comment by ahish-sujay** [comment]
Was extremely easy to figure out the read structure. Was able to demux/split for my files of interest in only 30 mins compared to other ones that took me more than a few days. Thanks for all the help and sorry for not digging a little deeper into the docs!

**Comment by nh13** [comment]
@ahish-sujay I am glad it worked!!!
