### ISSUE TITLE
how to obtain demultixepled paired-end reads with same structure as input reads, including cell barcodes / UMIs

### ISSUE THREAD

**Issue by andreiprodan** [fulcrumgenomics/fqtk#41]
first of all congrats on a great piece of software! 

I was wondering whether it's possible to set output options so as to obtain as output FASTQ files with the same structure as the input files (but split per e.g. cell barcode)

E.g. for a 10X 3' library, how to split to per-cell FASTQ so as to keep the structure of the resulting per-cell fastq file pairs the same as the inputs (so cell barcode and UMIs on R1, template on R2). Currently I can only figure out how to get either template reads out, or barcode reads, but not all. The **-b, --output-types** flag only accepts one value at a time

**Comment by nh13** [comment]
Can you try `--output-types M T B` (space-delimited)?

**Comment by andreiprodan** [comment]
that works, thanks!
